version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/whwtopia.kro.kr
hooks:
  BeforeInstall:
    - location: ../../../../prod_beforeinstall.sh
      timeout: 10000
      runas: root
  ValidateService:
    - location: scripts/validateservice.sh
      timeout: 10000
      runas: root