name: DEPLOY_DEV_SERVER
on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x.x

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: whwtopia-web-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: 'distZip'
