name: DEPLOY_DEV_SERVER
on: 
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

      - name: deploy yo s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: web-bucket-whwtopia-dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: 'dist'
