name: DEPLOY_DEV_SERVER
on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x.x

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

      - name: Zip
        run: |
          zip -r buildZip dist/* AppSpec.yml
          mkdir distZip
          mv buildZip.zip distZip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: deploy to s3
        run: aws s3 sync distZip/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: Code Deploy
        run: aws deploy create-deployment --application-name whwtopia-dev --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name fe --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=buildZip.zip